[tmp-fix] neps: unresolved path causes issue: (instead of going for site-packages, monkey patch):
File "/mnt/home/truhkopf/.conda/envs/ft-pfn/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/home/truhkopf/ExperiencedFT-PFNs/results/test/pfn-acq-1st-attempt/2025-05-26-15-23-56/neps_root_directory_29_0_0_42/results/config_1_0/../../all_losses_and_configs.txt'

fixed by just resolveing the working_directory path:

/mnt/home/truhkopf/.conda/envs/ft-pfn/lib/python3.10/site-packages/neps/api.py:

working_directory = Path(config_working_directory, "../../").resolve()